bpf: Fix compilation of bpf_ct_tests
b905f0d ("bpf: Compile test with tunneling disabled") broke the
compilation of bpf/tests/bpf_ct_tests as shown below:

    In file included from tests/bpf_ct_tests.c:41:
    In file included from /home/ubuntu/go/src/github.com/cilium/cilium/bpf/lib/conntrack.h:14:
    In file included from /home/ubuntu/go/src/github.com/cilium/cilium/bpf/lib/ipv4.h:10:
    In file included from /home/ubuntu/go/src/github.com/cilium/cilium/bpf/lib/metrics.h:13:
    /home/ubuntu/go/src/github.com/cilium/cilium/bpf/lib/maps.h:96:14: error: use of undeclared identifier 'TUNNEL_ENDPOINT_MAP_SIZE'
            .max_elem       = TUNNEL_ENDPOINT_MAP_SIZE,
                              ^
    In file included from tests/bpf_ct_tests.c:41:
    In file included from /home/ubuntu/go/src/github.com/cilium/cilium/bpf/lib/conntrack.h:14:
    /home/ubuntu/go/src/github.com/cilium/cilium/bpf/lib/ipv4.h:31:14: error: use of undeclared identifier 'CILIUM_IPV4_FRAG_MAP_MAX_ENTRIES'
            .max_elem       = CILIUM_IPV4_FRAG_MAP_MAX_ENTRIES,
                              ^
    2 errors generated.

The error was not detected because this test doesn't run in CI.

This commit fixes it by restoring the set of compile options used for
bpf_ct_tests before b905f0d.

Fixes: b905f0d ("bpf: Compile test with tunneling disabled")
Signed-off-by: Paul Chaignon <paul@cilium.io>